version: '3'
services:
  app:
    build: .
    command: ['bundle', 'exec', 'rails', 's', '-b', '0.0.0.0']
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      REDIS_URL: "redis://redis:6379/0"

    stdin_open: true
    tty: true

  mysql:
    image: 'mysql:5.7.16'
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  redis:
    image: "redis:4.0-alpine"
    volumes:
      - "./tmp/redis:/data"

  elasticsearch:
    image: 'elasticsearch:7.3.0'
    volumes:
      - ./tmp/elasticsearch/data:/usr/share/elasticsearch/data
